#!/usr/bin/env python3
"""Differential certification of sparse preflop/flop betting states.

The C authority is the bundled untouched CPRG/ACPC `game.c`.  This script
compiles only a line-protocol harness around it, then independently replays
each sparse path generated by hunl.early_street_tree.  It checks state,
raise window and validity of every emitted action.  No card values are used.
"""
from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path

from hunl.early_street_tree import EarlyStreetTreeBuilder, count_early_nodes

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
ORACLE = HERE / "betting_oracle"
GAME = HERE / "holdem.nolimit.2p.reverse_blinds.game"


def compile_oracle():
    cmd = ["cc", "-O2", "-std=gnu99", "-o", str(ORACLE),
           str(ROOT / "certification/hunl_g1/betting_oracle.c"),
           str(ROOT / "third_party/CFR_plus/game.c"),
           str(ROOT / "third_party/CFR_plus/rng.c"),
           "-I", str(ROOT / "third_party/CFR_plus")]
    subprocess.run(cmd, check=True, capture_output=True)


def oracle_query(path):
    lines = [f"G {GAME}", "N"]
    for a, size in path:
        lines.append("A " + ("f" if a == "fold" else
                             "c" if a == "call" else f"r{size}"))
    lines += ["S", "R", "Q f", "Q c"]
    p = subprocess.run([str(ORACLE)], input="\n".join(lines)+"\n",
                       text=True, capture_output=True, check=True)
    out = p.stdout.strip().splitlines()
    s = list(map(int, out[-4].split()[1:]))
    r = list(map(int, out[-3].split()[1:]))
    qf = int(out[-2].split()[1]); qc = int(out[-1].split()[1])
    return s, r, qf, qc


def replay_action_valid(path, action):
    lines = [f"G {GAME}", "N"]
    for a, size in path:
        lines.append("A " + ("f" if a == "fold" else
                             "c" if a == "call" else f"r{size}"))
    a, size = action
    lines.append("Q " + ("f" if a == "fold" else
                         "c" if a == "call" else f"r{size}"))
    p = subprocess.run([str(ORACLE)], input="\n".join(lines)+"\n",
                       text=True, capture_output=True, check=True)
    return int(p.stdout.strip().split()[-1])


def validate_tree(root, start_round):
    checked = actions = 0
    failures = []
    boundary_paths = []

    def walk(n, path):
        nonlocal checked, actions
        s, r, qf, qc = oracle_query(path)
        # S: finished round cur spent0 spent1 max minRaise folded0 folded1
        fin, rnd, cur, sp0, sp1, mx, mn, f0, f1 = s
        checked += 1
        if n.terminal == "fold":
            exp_fin = 1
            if not fin:
                failures.append((path, "fold-not-finished", s))
            return
        if n.terminal == "allin_runout":
            if not fin:
                failures.append((path, "allin-not-finished", s))
            return
        if n.is_boundary:
            if fin:
                failures.append((path, "boundary-finished", s))
            expected_round = start_round + 1
            if (rnd, sp0, sp1, mx, mn) != (expected_round, n.spent[0],
                    n.spent[1], n.max_spent, n.min_raise_to):
                failures.append((path, "boundary-state", s,
                                 (expected_round, *n.spent, n.max_spent,
                                  n.min_raise_to)))
            boundary_paths.append((path, n))
            return
        if fin:
            failures.append((path, "decision-finished", s))
            return
        if (rnd, cur, sp0, sp1, mx, mn) != (
                start_round, n.player, n.spent[0], n.spent[1],
                n.max_spent, n.min_raise_to):
            failures.append((path, "state", s,
                             (start_round, n.player, *n.spent,
                              n.max_spent, n.min_raise_to)))
        if bool(qf) != any(a[0] == "fold" for a in n.actions):
            # Table-4 never intentionally removes fold; compare directly.
            failures.append((path, "fold-validity", qf, n.actions))
        if qc != 1 or not any(a[0] == "call" for a in n.actions):
            failures.append((path, "call-validity", qc, n.actions))
        rv, rmn, rmx = r
        # Our builder uses the same ACPC raise-window mirror; exact window.
        has_raise = any(a[0] == "raise" for a in n.actions)
        if bool(rv) != (rmn <= rmx and n.max_spent < 20000 and
                        n.spent[1-n.player] < 20000):
            # Informational only; emitted raises below are authoritative.
            pass
        for a in n.actions:
            actions += 1
            if not replay_action_valid(path, a):
                failures.append((path, "emitted-invalid", a, r))
        for a, c in zip(n.actions, n.children):
            walk(c, path + [a])

    walk(root, [])
    return checked, actions, failures, boundary_paths


def main():
    compile_oracle()
    pre = EarlyStreetTreeBuilder("preflop").build_preflop()
    pc = count_early_nodes(pre)
    checked, acts, fail, boundaries = validate_tree(pre, 0)
    if fail:
        raise AssertionError(f"preflop divergence: {fail[0]}")

    # Validate flop trees only for pot-halves actually produced by the
    # certified sparse preflop tree.  Board cards do not affect betting
    # legality, so one fixed legal flop board is sufficient for this gate.
    pots = sorted({n.max_spent for _, n in boundaries})
    flop_summary = {}
    total_checked = checked; total_acts = acts
    # To replay a flop node we need the full preflop path that reached it.
    # Build/validate one flop tree per distinct boundary path (small sparse set).
    for path, b in boundaries:
        fb = EarlyStreetTreeBuilder("flop").build_flop((0, 1, 2), b.max_spent)
        fc = count_early_nodes(fb)
        # custom validation with preflop prefix
        def walk_flop(n, fpath):
            nonlocal total_checked, total_acts
            full = path + fpath
            s, r, qf, qc = oracle_query(full)
            fin, rnd, cur, sp0, sp1, mx, mn, f0, f1 = s
            total_checked += 1
            if n.terminal == "fold":
                if not fin: raise AssertionError((full, "fold-not-finished", s))
                return
            if n.terminal == "allin_runout":
                if not fin: raise AssertionError((full, "allin-not-finished", s))
                return
            if n.is_boundary:
                if fin: raise AssertionError((full, "boundary-finished", s))
                if (rnd, sp0, sp1, mx, mn) != (2, *n.spent, n.max_spent,
                                                n.min_raise_to):
                    raise AssertionError((full, "flop-boundary-state", s, n))
                return
            if (fin or (rnd, cur, sp0, sp1, mx, mn) !=
                    (1, n.player, *n.spent, n.max_spent, n.min_raise_to)):
                raise AssertionError((full, "flop-state", s, n))
            if bool(qf) != any(a[0] == "fold" for a in n.actions):
                raise AssertionError((full, "flop-fold-validity", qf, n.actions))
            if qc != 1: raise AssertionError((full, "flop-call-invalid"))
            for a in n.actions:
                total_acts += 1
                if not replay_action_valid(full, a):
                    raise AssertionError((full, "flop-emitted-invalid", a, r))
            for a,c in zip(n.actions,n.children): walk_flop(c, fpath+[a])
        walk_flop(fb, [])
        flop_summary[str(b.max_spent)] = fc

    manifest = {
        "schema": "HUNL_EARLY_STREET_ORACLE_V1",
        "preflop": pc,
        "distinct_flop_pot_halves": pots,
        "flop_counts_by_pot_half": flop_summary,
        "oracle_nodes_checked": total_checked,
        "emitted_actions_checked": total_acts,
        "divergences": 0,
        "authority": "bundled untouched CPRG/ACPC game.c",
        "sparse_menus": "DeepStack supplement Table 4",
    }
    blob = json.dumps(manifest, sort_keys=True, separators=(",", ":")).encode()
    manifest["fingerprint_sha256"] = hashlib.sha256(blob).hexdigest()
    out = HERE / "EARLY_STREET_ORACLE.json"
    out.write_text(json.dumps(manifest, indent=2)+"\n")
    print(json.dumps(manifest, indent=2))

if __name__ == "__main__":
    main()
