#!/usr/bin/env python3
"""HUNL TURN DATAGENERATOR — post-generation certification harness.

Prerequisite: pilot shards + replay0 generated by hunl_datagen/turn_datagen.py.

Sections:
  1. Shard manifests + dataset SHA anchors + RNG ledger reconciliation
  2. Full-shard replay certification (shard 0 fresh-process regeneration
     must be byte-identical, all five arrays)
  3. Row-level inversion audit: serialized row -> reconstruct
     board/ranges/pot -> fresh frozen-engine resolve -> byte-identical
     f32 target vector (deterministic stack => BYTE_EXACT required)
  4. Independent target oracles:
     A. forced-check/all-in oracle: sampled boards+ranges, no-raise
        config == solver-free all-in equity (machine precision)
     B. LP small-support states solved with the DATAGEN action set
        {F,C,P,A} at 1000/500 vs exact sequence-form LP
  5. Statistical QA (boards, pots, ranges, targets, duplicates,
     zero-sum, independence sanity)
  6. Frozen-regression battery driver is run separately
     (run_turn_engine_regression.py) + v1 determinism SHA re-anchor.

Run from DS root:
  LD_LIBRARY_PATH=$PWD PYTHONPATH=/home/user/quant-trade:. \
      python3 /home/user/quant-trade/certification/hunl_g1/run_turn_datagen_cert.py
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

np.seterr(all="ignore")
QT = Path("/home/user/quant-trade")
DS = Path("/workspace/deepstack_leduc_v1.1-bitexact-certified")
sys.path.insert(0, str(QT))
sys.path.insert(0, str(QT / "certification/hunl_g1"))

from hunl.cards import HAND_COUNT, possible_hands_mask  # noqa: E402
from hunl.turn import all_in_equity  # noqa: E402
from hunl.turn_engine import TurnEngine  # noqa: E402
from hunl_datagen.turn_datagen import (CFR_ITERS, CFR_OMIT,  # noqa: E402
                                       CONFIG_SHA, DGCFG, ENGINE_SHA,
                                       POT_INTERVALS, shard_seed)
from turn_oracles import solve_turn_lp  # noqa: E402

T0 = time.time()
report: list[str] = []
PILOT = QT / "certification/hunl_datagen_pilot"
SHARDS = PILOT / "shards"
N_SHARDS = 12
SHARD_N = 20
ENV = {**os.environ, "LD_LIBRARY_PATH": str(DS),
       "PYTHONPATH": f"{QT}:{QT / 'certification/hunl_g1'}:{DS}",
       "OPENBLAS_NUM_THREADS": "1", "OMP_NUM_THREADS": "1"}


def log(m):
    print(m, flush=True)
    report.append(m)


def sha_file(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def load_shard(prefix: Path):
    return {name: np.load(f"{prefix}.{name}.npy")
            for name in ("boards", "pots", "ranges", "targets", "masks")}


# ---------------- 1. manifests, anchors, RNG ledger reconciliation ----
log("== 1. shard manifests + anchors + RNG ledger ==")
manifests = []
anchor_lines = []
for s in range(N_SHARDS):
    prefix = SHARDS / f"shard_{s:05d}"
    m = json.loads(Path(f"{prefix}.json").read_text())
    assert m["samples"] == SHARD_N and m["seed"] == shard_seed(s)
    assert m["config_sha"] == CONFIG_SHA and m["engine_sha"] == ENGINE_SHA
    for name in ("boards", "pots", "ranges", "targets", "masks"):
        assert sha_file(Path(f"{prefix}.{name}.npy")) == m["sha256"][name], \
            f"shard {s} {name} SHA drift"
    led = m["rng_ledger"]
    batches = SHARD_N // 10
    assert led["board_draws"] == 4 * batches + led["board_rejects"]
    assert led["pot_draws"] == 2 * SHARD_N
    # ranges: 2 players x (1127 nodes x 10 rand) + odd-split draws
    base = 2 * 1127 * 10 * batches
    odd = led["range_draws"] - base
    assert odd == 752 * batches, f"shard {s} odd-split draws {odd}"
    assert m["total_draws"] == led["board_draws"] + led["range_draws"] \
        + led["pot_draws"]
    manifests.append(m)
    anchor_lines.append(f"{s}:{m['seed']}:" + ",".join(
        m["sha256"][k] for k in sorted(m["sha256"])))
combined = hashlib.sha256("\n".join(anchor_lines).encode()).hexdigest()
runtime_min = [m["gen_minutes"] for m in manifests]
log(f"1 PASS: {N_SHARDS} shards x {SHARD_N} samples; every manifest SHA "
    f"verified; RNG ledger reconciles exactly (4+rej board, 22,540+752 "
    f"range, 40 pot draws per shard); per-shard runtime "
    f"min/med/max = {min(runtime_min):.0f}/"
    f"{sorted(runtime_min)[len(runtime_min)//2]:.0f}/"
    f"{max(runtime_min):.0f} min")
log(f"dataset combined SHA-256 anchor: {combined}")

# ------------------------------- 2. full-shard replay certification --
log("== 2. full-shard replay (fresh process, byte-identity) ==")
rep = PILOT / "replay0" / "shard_00000"
orig = SHARDS / "shard_00000"
for name in ("boards", "pots", "ranges", "targets", "masks"):
    a = sha_file(Path(f"{orig}.{name}.npy"))
    b = sha_file(Path(f"{rep}.{name}.npy"))
    assert a == b, f"replay divergence in {name}"
log("2 PASS: shard 0 fully regenerated in a fresh process — all five "
    "arrays byte-identical (BYTE_EXACT)")

# --------------------------------------- 3. row inversion audit ------
log("== 3. row-level inversion audit (byte-exact target replay) ==")
t = time.time()
rng = np.random.default_rng(20260814)
rows = sorted(rng.choice(N_SHARDS * SHARD_N, size=8, replace=False).tolist())
audited = []
for gr in rows:
    s, r = divmod(gr, SHARD_N)
    d = load_shard(SHARDS / f"shard_{s:05d}")
    board = tuple(int(c) for c in d["boards"][r])
    pot = int(d["pots"][r])
    r1 = d["ranges"][r, 0].astype(np.float64)
    r2 = d["ranges"][r, 1].astype(np.float64)
    pm = possible_hands_mask(board)
    assert (d["masks"][r] == pm.astype(np.uint8)).all()
    te = TurnEngine(board, pot, cfg=DGCFG)
    cfvs = te.resolve_first_node(r1, r2)
    tgt = (cfvs / float(pot)).astype(np.float32)
    assert tgt.tobytes() == d["targets"][r].tobytes(), \
        f"INVERSION DIVERGENCE shard {s} row {r}"
    audited.append(gr)
    log(f"  row {gr} (shard {s}, row {r}, pot {pot}): target replay "
        f"BYTE-IDENTICAL [{(time.time()-t)/60:.0f} min]")
log(f"3 PASS: {len(rows)} rows byte-exact ({(time.time()-t)/60:.0f} min)")

# --------------------------------- 4. independent target oracles -----
log("== 4. independent oracles ==")
t = time.time()
import dataclasses  # noqa: E402
NOB = dataclasses.replace(DGCFG, turn_menus=((), (), ()),
                          turn_allin=False, river_allin=False)
d = load_shard(SHARDS / "shard_00001")
for r in (0, 10):
    board = tuple(int(c) for c in d["boards"][r])
    pot = int(d["pots"][r])
    r1 = d["ranges"][r, 0].astype(np.float64)
    r2 = d["ranges"][r, 1].astype(np.float64)
    te = TurnEngine(board, pot, cfg=NOB, cfr_iters=4, cfr_skip_iters=2)
    cfvs = te.resolve_first_node(r1, r2)
    ref = all_in_equity(board, pot, r1, r2)
    dmax = np.abs(cfvs - ref).max() / pot
    assert dmax < 1e-12, f"forced-check oracle {dmax}"
    log(f"  A forced-check/all-in oracle row {r}: |d| {dmax:.2e} of pot")
lp_rng = np.random.default_rng(7)
for r in (3, 15):
    board = tuple(int(c) for c in d["boards"][r])
    pot = int(d["pots"][r])
    pm = possible_hands_mask(board)
    live = np.nonzero(pm)[0]
    s1 = sorted(lp_rng.choice(live, 6, replace=False).tolist())
    s2 = sorted(lp_rng.choice(live, 6, replace=False).tolist())
    r1 = np.zeros(HAND_COUNT); r1[s1] = lp_rng.random(6) + 0.1
    r1 /= r1.sum()
    r2 = np.zeros(HAND_COUNT); r2[s2] = lp_rng.random(6) + 0.1
    r2 /= r2.sum()
    v_lp = solve_turn_lp(board, pot, s1, s2, r1, r2, DGCFG)
    te = TurnEngine(board, pot, cfg=DGCFG)
    cfvs = te.resolve_first_node(r1, r2)
    v_en = float(r1 @ cfvs[0])
    rel = abs(v_en - v_lp) / (2 * pot)
    assert rel < 0.005, f"LP oracle {rel}"
    log(f"  C LP small-support (datagen menus, 1000/500) board "
        f"{d['boards'][r].tolist()} pot {pot}: |d| {rel*100:.3f}% pot")
log(f"4 PASS ({(time.time()-t)/60:.0f} min)")

# ----------------------------------------- 5. statistical QA ---------
log("== 5. statistical QA over the pilot ==")
allb = []
allp = []
row_hashes = set()
dup = 0
zsum_max = 0.0
tmax_rel = 0.0
support_sizes = []
for s in range(N_SHARDS):
    d = load_shard(SHARDS / f"shard_{s:05d}")
    allb.append(d["boards"])
    allp.append(d["pots"])
    for r in range(SHARD_N):
        pm = d["masks"][r].astype(bool)
        rr = d["ranges"][r]
        tt = d["targets"][r]
        assert np.isfinite(rr).all() and np.isfinite(tt).all()
        assert (rr[:, ~pm] == 0).all() and (tt[:, ~pm] == 0).all()
        sums = rr.sum(axis=1)
        assert (sums > 0.999).all() and (sums < 1.001).all()
        pot = float(d["pots"][r])
        assert np.abs(tt).max() <= 20000.0 / pot + 1e-6
        tmax_rel = max(tmax_rel, float(np.abs(tt).max() / (20000.0 / pot)))
        zs = abs(float(rr[0].astype(np.float64) @ tt[0]
                       + rr[1].astype(np.float64) @ tt[1])) / 2.0
        zsum_max = max(zsum_max, zs)
        h = hashlib.sha256(rr.tobytes() + d["boards"][r].tobytes()
                           + d["pots"][r].tobytes()).digest()
        if h in row_hashes:
            dup += 1
        row_hashes.add(h)
        support_sizes.append(int((rr > 0).sum(axis=1).mean()))
allb = np.concatenate(allb)
allp = np.concatenate(allp)
cards = allb.ravel()
counts = np.bincount(cards, minlength=52)
chi2 = float(((counts - counts.mean()) ** 2 / counts.mean()).sum())
cats = np.zeros(5, dtype=int)
for p in allp:
    for k, (lo, hi) in enumerate(POT_INTERVALS):
        if lo <= p <= hi:
            cats[k] += 1
assert dup == 0
assert zsum_max < 1e-2, f"zero-sum residual {zsum_max}"
# independence sanity: consecutive-sample pot correlation
pc = np.corrcoef(allp[:-1], allp[1:])[0, 1]
log(f"5 PASS: {N_SHARDS*SHARD_N} samples; board-card chi2 {chi2:.1f} "
    f"(df 51); pot categories {cats.tolist()} (uniform 20% each, "
    f"n={len(allp)}); pot min/max {allp.min()}/{allp.max()}; range sums "
    f"in (0.999,1.001); blocked zero; 0 duplicates; max |t| at "
    f"{tmax_rel*100:.1f}% of stack/pot bound; max zero-sum residual "
    f"{zsum_max:.2e} (f32 targets); consecutive-pot corr {pc:+.3f}; "
    f"mean support {np.mean(support_sizes):.0f} hands")

log(f"\nDATAGEN CERT CORE: PASS ({(time.time()-T0)/60:.1f} min)")
out = QT / "certification/hunl_g1/latest_audit"
out.mkdir(exist_ok=True)
(out / "TURN_DATAGEN_CERT_RESULT.txt").write_text("\n".join(report) + "\n")
(out / "TURN_DATAGEN_ANCHORS.txt").write_text(
    "\n".join(anchor_lines) + f"\ncombined:{combined}\n")
